# Generated by Django 2.2.1 on 2019-05-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_device_borrow_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=50)),
                ('conference_room', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
                ('borrower', models.CharField(max_length=20)),
                ('borrow_time', models.DateTimeField(auto_now_add=True)),
                ('expected_time', models.CharField(max_length=50)),
                ('actual_time', models.CharField(max_length=50)),
                ('remark', models.CharField(max_length=100)),
            ],
        ),
    ]
