# Generated by Django 2.2.1 on 2019-05-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='remark',
            field=models.CharField(choices=[('NO', 'No'), ('YES', 'Yes')], default='NO', max_length=20),
        ),
    ]
