# Generated by Django 2.2.1 on 2019-05-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0006_auto_20190525_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='actual_time',
            field=models.DateTimeField(blank=True, default='', null=True, verbose_name='实际归还时间'),
        ),
        migrations.AlterField(
            model_name='device',
            name='borrow_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='借用日期'),
        ),
        migrations.AlterField(
            model_name='device',
            name='borrower',
            field=models.CharField(max_length=20, verbose_name='借用人'),
        ),
        migrations.AlterField(
            model_name='device',
            name='conference_room',
            field=models.CharField(max_length=20, verbose_name='使用地点'),
        ),
        migrations.AlterField(
            model_name='device',
            name='department',
            field=models.CharField(max_length=20, verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_name',
            field=models.CharField(max_length=50, verbose_name='设备名称'),
        ),
        migrations.AlterField(
            model_name='device',
            name='expected_time',
            field=models.CharField(max_length=50, verbose_name='预计归还日期'),
        ),
        migrations.AlterField(
            model_name='device',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='device',
            name='remark',
            field=models.CharField(choices=[('NO', 'No'), ('YES', 'Yes')], default='NO', max_length=20, verbose_name='备注'),
        ),
    ]
