# Generated by Django 2.2.1 on 2019-05-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0007_auto_20190525_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='actual_time',
            field=models.CharField(default=1, max_length=10, verbose_name='实际归还时间'),
            preserve_default=False,
        ),
    ]
