# Generated by Django 2.2.1 on 2019-05-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0008_auto_20190525_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='actual_time',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='实际归还时间'),
        ),
    ]
