# Generated by Django 2.2.1 on 2019-05-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0009_auto_20190525_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='actual_time',
            field=models.CharField(blank=True, default='未归还', max_length=20, null=True, verbose_name='实际归还时间'),
        ),
        migrations.AlterField(
            model_name='device',
            name='expected_time',
            field=models.CharField(max_length=20, verbose_name='预计归还日期'),
        ),
    ]
