# Generated by Django 2.2.1 on 2019-05-25 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0010_auto_20190525_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='borrower',
            field=models.CharField(max_length=20, verbose_name='借  用  人'),
        ),
        migrations.AlterField(
            model_name='device',
            name='department',
            field=models.CharField(max_length=20, verbose_name='部    门'),
        ),
        migrations.AlterField(
            model_name='device',
            name='remark',
            field=models.CharField(choices=[('未归还', '未归还'), ('已归还', '已归还')], default='未归还', max_length=20, verbose_name='备注'),
        ),
    ]
